name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - ghc-9.4
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-18.04
        ghc:
          - 9.4.2
        include:
          - os: macos-latest
            ghc: system
          - os: windows-latest
            ghc: system
    steps:
      - uses: actions/checkout@v3
      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - run: cabal update
      - run: cabal configure --enable-tests --enable-benchmarks
      - run: cabal build all
      - run: cabal exec -- cabal repl --with-ghc=doctest

  success:
    needs: build
    runs-on: ubuntu-latest
    if: always() # this is required as GitHub considers "skipped" jobs as "passed" when checking branch protection rules

    steps:
      - run: false
        if: needs.build.result != 'success'
